/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WsLabRouteImport } from './routes/ws-lab'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const WsLabRoute = WsLabRouteImport.update({
  id: '/ws-lab',
  path: '/ws-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/habits': typeof HabitsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/ws-lab': typeof WsLabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/habits': typeof HabitsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/ws-lab': typeof WsLabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/habits': typeof HabitsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/ws-lab': typeof WsLabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analytics' | '/habits' | '/settings' | '/tasks' | '/ws-lab'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analytics' | '/habits' | '/settings' | '/tasks' | '/ws-lab'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/habits'
    | '/settings'
    | '/tasks'
    | '/ws-lab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  HabitsRoute: typeof HabitsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  WsLabRoute: typeof WsLabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ws-lab': {
      id: '/ws-lab'
      path: '/ws-lab'
      fullPath: '/ws-lab'
      preLoaderRoute: typeof WsLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  HabitsRoute: HabitsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  WsLabRoute: WsLabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
